[
 {
   "BuildingName": "4-H Center",
   "Address": "2201 Fred Taylor Dr",
   "ElevatorNumber": "1",
   "AssetNumber": "49875",
   "ElevatorType": "Public",
   "BuildingNumber": 191,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "930 Kinnear Rd",
   "Address": "930 Kinnear Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "49549",
   "ElevatorType": "Staff",
   "BuildingNumber": 227,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Agricultural Administration",
   "Address": "2120 Fyffe Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "6347",
   "ElevatorType": "Public",
   "BuildingNumber": 3,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Agricultural Administration",
   "Address": "2120 Fyffe Rd",
   "ElevatorNumber": "3 - Library",
   "AssetNumber": "62492",
   "ElevatorType": "Public",
   "BuildingNumber": 3,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Agricultural Engineering Building",
   "Address": "590 Woody Hayes Dr",
   "ElevatorNumber": "1",
   "AssetNumber": "28644",
   "ElevatorType": "Public",
   "BuildingNumber": 298,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Animal Science Building",
   "Address": "2029 Fyffe Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "341",
   "ElevatorType": "Public",
   "BuildingNumber": 156,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Aronoff Laboratory",
   "Address": "318 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "45045",
   "ElevatorType": "Public",
   "BuildingNumber": 131,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Aronoff Laboratory",
   "Address": "318 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "45046",
   "ElevatorType": "Public",
   "BuildingNumber": 131,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Arps Hall",
   "Address": "1945 N High Street",
   "ElevatorNumber": "1",
   "AssetNumber": "31709",
   "ElevatorType": "Freight",
   "BuildingNumber": 11,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Arps Hall",
   "Address": "1945 N High Street",
   "ElevatorNumber": "2",
   "AssetNumber": "42352",
   "ElevatorType": "Public",
   "BuildingNumber": 11,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Arps Hall",
   "Address": "1945 N High St",
   "ElevatorNumber": "3",
   "AssetNumber": "9320",
   "ElevatorType": "Public",
   "BuildingNumber": 11,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Atwell Hall",
   "Address": "453 W 10th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "689",
   "ElevatorType": "Public",
   "BuildingNumber": 306,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Atwell Hall",
   "Address": "453 W 10th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "691",
   "ElevatorType": "Public",
   "BuildingNumber": 306,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Atwell Hall",
   "Address": "453 W 10th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "744",
   "ElevatorType": "Public",
   "BuildingNumber": 306,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Baker Systems Engineering",
   "Address": "1971 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "2583",
   "ElevatorType": "Public",
   "BuildingNumber": 280,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Baker Systems Engineering",
   "Address": "1971 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "2584",
   "ElevatorType": "Public",
   "BuildingNumber": 280,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Baker Systems Engineering",
   "Address": "1971 Neil Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "2585",
   "ElevatorType": "Staff",
   "BuildingNumber": 280,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Bevis Hall",
   "Address": "1080 Carmack Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "301",
   "ElevatorType": "Staff",
   "BuildingNumber": 307,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biological Science Building",
   "Address": "484 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "519",
   "ElevatorType": "Public",
   "BuildingNumber": 276,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biological Science Building",
   "Address": "484 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "520",
   "ElevatorType": "Public",
   "BuildingNumber": 276,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biological Science Building",
   "Address": "484 W 12th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "521",
   "ElevatorType": "Public",
   "BuildingNumber": 276,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biological Science Building",
   "Address": "484 W 12th Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "528",
   "ElevatorType": "Freight",
   "BuildingNumber": 276,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biological Science Greenhouse Garage",
   "Address": "484 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "45043",
   "ElevatorType": "Public",
   "BuildingNumber": 283,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biomedical Research Tower",
   "Address": "460 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "47625",
   "ElevatorType": "Public",
   "BuildingNumber": 112,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biomedical Research Tower",
   "Address": "460 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "47626",
   "ElevatorType": "Public",
   "BuildingNumber": 112,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biomedical Research Tower",
   "Address": "460 W 12th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "47627",
   "ElevatorType": "Public",
   "BuildingNumber": 112,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biomedical Research Tower",
   "Address": "460 W 12th Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "49100",
   "ElevatorType": "Public",
   "BuildingNumber": 112,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biomedical Research Tower",
   "Address": "460 W 12th Ave",
   "ElevatorNumber": "5",
   "AssetNumber": "47628",
   "ElevatorType": "Public",
   "BuildingNumber": 112,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biomedical Research Tower",
   "Address": "460 W 12th Ave",
   "ElevatorNumber": "6",
   "AssetNumber": "47629",
   "ElevatorType": "Public",
   "BuildingNumber": 112,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biomedical Research Tower",
   "Address": "460 W 12th Ave",
   "ElevatorNumber": "7",
   "AssetNumber": "47630",
   "ElevatorType": "Public",
   "BuildingNumber": 112,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biomedical Research Tower Chairlift",
   "Address": "460 W 12th Ave",
   "ElevatorNumber": "8",
   "AssetNumber": "49133",
   "ElevatorType": "Public",
   "BuildingNumber": 112,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Biotechnology Support Facility",
   "Address": "1060 Carmack Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "32715",
   "ElevatorType": "Public",
   "BuildingNumber": 394,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Blankenship Hall",
   "Address": "901 Woody Hayes Dr",
   "ElevatorNumber": "1-East",
   "AssetNumber": "26213",
   "ElevatorType": "Public",
   "BuildingNumber": 360,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Blankenship Hall",
   "Address": "901 Woody Hayes Dr",
   "ElevatorNumber": "2-Center Elevator",
   "AssetNumber": "26214",
   "ElevatorType": "Public",
   "BuildingNumber": 360,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Bolz Hall",
   "Address": "2036 Neil Ave Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "9330",
   "ElevatorType": "Public",
   "BuildingNumber": 146,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Bricker Hall",
   "Address": "190 N Oval Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "1369",
   "ElevatorType": "Public",
   "BuildingNumber": 1,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Caldwell Laboratory",
   "Address": "2024 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "33724",
   "ElevatorType": "Freight",
   "BuildingNumber": 26,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Campbell Hall",
   "Address": "1787 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "34289",
   "ElevatorType": "Public",
   "BuildingNumber": 18,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Campbell Hall",
   "Address": "1787 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "6938",
   "ElevatorType": "Public",
   "BuildingNumber": 18,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "CBEC",
   "Address": "151 W Woodruff Ave",
   "ElevatorNumber": "1-A",
   "AssetNumber": "61255",
   "ElevatorType": "Public",
   "BuildingNumber": 248,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "CBEC",
   "Address": "151 W Woodruff Ave",
   "ElevatorNumber": "2-B",
   "AssetNumber": "61256",
   "ElevatorType": "Public",
   "BuildingNumber": 248,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "CBEC",
   "Address": "151 W Woodruff Ave",
   "ElevatorNumber": "3-C",
   "AssetNumber": "61257",
   "ElevatorType": "Public",
   "BuildingNumber": 248,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Celeste Laboratoy of Chemistry",
   "Address": "120 W 18th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "27267",
   "ElevatorType": "Public",
   "BuildingNumber": 371,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Celeste Laboratoy of Chemistry",
   "Address": "120 W 18th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "28612",
   "ElevatorType": "Staff",
   "BuildingNumber": 371,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Cockins Hall",
   "Address": "1958 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "42242",
   "ElevatorType": "Public",
   "BuildingNumber": 63,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Comprehensive Cancer Center",
   "Address": "410 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "25840",
   "ElevatorType": "Public",
   "BuildingNumber": 363,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Converse Hall",
   "Address": "2121 Tuttle Park Pl",
   "ElevatorNumber": "1",
   "AssetNumber": "42241",
   "ElevatorType": "Public",
   "BuildingNumber": 56,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Cunz Hall",
   "Address": "1841 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "52690",
   "ElevatorType": "Public",
   "BuildingNumber": 293,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Cunz Hall",
   "Address": "1841 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "52691",
   "ElevatorType": "Public",
   "BuildingNumber": 293,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Davis Heart & Lung Research Institute",
   "Address": "473 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "41891",
   "ElevatorType": "Public",
   "BuildingNumber": 113,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Davis Heart & Lung Research Institute",
   "Address": "473 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "41889",
   "ElevatorType": "Staff",
   "BuildingNumber": 113,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Davis Heart & Lung Research Institute",
   "Address": "473 W 12th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "41890",
   "ElevatorType": "Public",
   "BuildingNumber": 113,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Denny Hall",
   "Address": "164 Annie & John Glenn Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "147",
   "ElevatorType": "Public",
   "BuildingNumber": 30,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Denny Hall",
   "Address": "164 Annie & John Glenn Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "148",
   "ElevatorType": "Public",
   "BuildingNumber": 30,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Derby Hall",
   "Address": "154 N Oval Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "22514",
   "ElevatorType": "Public",
   "BuildingNumber": 25,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Dreese Laboratories",
   "Address": "2015 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "33422",
   "ElevatorType": "Public",
   "BuildingNumber": 279,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Dreese Laboratories",
   "Address": "2015 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "163",
   "ElevatorType": "Public",
   "BuildingNumber": 279,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Dreese Laboratories",
   "Address": "2015 Neil Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "162",
   "ElevatorType": "Public",
   "BuildingNumber": 279,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Dreese Laboratories",
   "Address": "2015 Neil Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "33419",
   "ElevatorType": "Public",
   "BuildingNumber": 279,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Dreese Laboratories",
   "Address": "2015 Neil Ave",
   "ElevatorNumber": "5",
   "AssetNumber": "33418",
   "ElevatorType": "Public",
   "BuildingNumber": 279,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Drinko Hall",
   "Address": "55 W 12th Ave",
   "ElevatorNumber": "1-Library",
   "AssetNumber": "32006",
   "ElevatorType": "Public",
   "BuildingNumber": 49,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Drinko Hall",
   "Address": "55 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "32007",
   "ElevatorType": "Public",
   "BuildingNumber": 49,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Drinko Hall",
   "Address": "55 W 12th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "9326",
   "ElevatorType": "Staff",
   "BuildingNumber": 49,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Drinko Hall",
   "Address": "55 W 12th Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "62150",
   "ElevatorType": "Public",
   "BuildingNumber": 49,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Dulles Hall",
   "Address": "230 Annie & John Glenn Ave",
   "ElevatorNumber": "1-B",
   "AssetNumber": "22546",
   "ElevatorType": "Public",
   "BuildingNumber": 337,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Dulles Hall",
   "Address": "230 Annie & John Glenn Ave",
   "ElevatorNumber": "2-South",
   "AssetNumber": "22547",
   "ElevatorType": "Public",
   "BuildingNumber": 337,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Eighteenth Ave, 209 W",
   "Address": "209 W 18th Avenue",
   "ElevatorNumber": "1",
   "AssetNumber": "TBD",
   "ElevatorType": "Public",
   "BuildingNumber": 4,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Eighteenth Avenue Library",
   "Address": "175 W 18th Avenue",
   "ElevatorNumber": "1",
   "AssetNumber": "32413",
   "ElevatorType": "Public",
   "BuildingNumber": 5,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Eighteenth Avenue Library",
   "Address": "175 W 18th Avenue",
   "ElevatorNumber": "2",
   "AssetNumber": "32414",
   "ElevatorType": "Public",
   "BuildingNumber": 5,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Eighteenth Avenue Library",
   "Address": "175 W 18th Avenue",
   "ElevatorNumber": "3",
   "AssetNumber": "32429",
   "ElevatorType": "Staff",
   "BuildingNumber": 5,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Electroscience Laboratory",
   "Address": "1320 Kinnear Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "47920",
   "ElevatorType": "Public",
   "BuildingNumber": 9,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Eleventh Ave, 33 W",
   "Address": "33 W 11th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "1206",
   "ElevatorType": "Public",
   "BuildingNumber": 193,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Eleventh Ave, 33 W",
   "Address": "33 W 11th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "35084",
   "ElevatorType": "Public",
   "BuildingNumber": 193,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Enarson Classroom Building",
   "Address": "2009 Millikin Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "30579",
   "ElevatorType": "Public",
   "BuildingNumber": 72,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Enarson Classroom Building",
   "Address": "2009 Millikin Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "30580",
   "ElevatorType": "Staff",
   "BuildingNumber": 72,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Enarson Classroom Building",
   "Address": "2009 Millikin Rd",
   "ElevatorNumber": "3",
   "AssetNumber": "30581",
   "ElevatorType": "Public",
   "BuildingNumber": 72,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Evans Laboratory",
   "Address": "88 W 18th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "340",
   "ElevatorType": "Public",
   "BuildingNumber": 150,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Faculty Club",
   "Address": "181 S Oval Dr",
   "ElevatorNumber": "1",
   "AssetNumber": "5012",
   "ElevatorType": "Public",
   "BuildingNumber": 28,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Faculty Club",
   "Address": "181 S Oval Dr",
   "ElevatorNumber": "2",
   "AssetNumber": "31269",
   "ElevatorType": "Staff",
   "BuildingNumber": 28,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Faculty Club",
   "Address": "181 S Oval Dr",
   "ElevatorNumber": "3",
   "AssetNumber": "36483",
   "ElevatorType": "Public",
   "BuildingNumber": 28,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Faculty Club",
   "Address": "181 S Oval Dr",
   "ElevatorNumber": "4",
   "AssetNumber": "47743",
   "ElevatorType": "Public",
   "BuildingNumber": 28,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Faculty Club",
   "Address": "181 S Oval Dr",
   "ElevatorNumber": "5",
   "AssetNumber": "60034",
   "ElevatorType": "Public",
   "BuildingNumber": 28,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Fisher Hall",
   "Address": "2100 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "35787",
   "ElevatorType": "Public",
   "BuildingNumber": 249,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Fisher Hall",
   "Address": "2100 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "35788",
   "ElevatorType": "Staff",
   "BuildingNumber": 249,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Fisher Hall",
   "Address": "2100 Neil Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "35789",
   "ElevatorType": "Public",
   "BuildingNumber": 249,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Fry Hall",
   "Address": "338 W 10th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "48517",
   "ElevatorType": "Public",
   "BuildingNumber": 59,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Fry Hall",
   "Address": "338 W 10th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "48634",
   "ElevatorType": "Public",
   "BuildingNumber": 59,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Galbreath Equine Center",
   "Address": "685 Vernon Tharp St",
   "ElevatorNumber": "1",
   "AssetNumber": "34672",
   "ElevatorType": "Public",
   "BuildingNumber": 282,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Gerlach Hall",
   "Address": "2108 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "35782",
   "ElevatorType": "Public",
   "BuildingNumber": 250,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Gerlach Hall",
   "Address": "2108 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "35783",
   "ElevatorType": "Public",
   "BuildingNumber": 250,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Goss Laboratory",
   "Address": "1925 Coffey Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "1203",
   "ElevatorType": "Public",
   "BuildingNumber": 180,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Goss Laboratory",
   "Address": "1925 Coffey Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "1204",
   "ElevatorType": "Freight",
   "BuildingNumber": 180,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Graves Hall",
   "Address": "333 W 10th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "422",
   "ElevatorType": "Public",
   "BuildingNumber": 277,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Graves Hall",
   "Address": "333 W 10th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "423",
   "ElevatorType": "Public",
   "BuildingNumber": 277,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Graves Hall",
   "Address": "333 W 10th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "424",
   "ElevatorType": "Public",
   "BuildingNumber": 277,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Graves Hall",
   "Address": "333 W 10th Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "425",
   "ElevatorType": "Public",
   "BuildingNumber": 277,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Graves Hall",
   "Address": "333 W 10th Ave",
   "ElevatorNumber": "5",
   "AssetNumber": "433",
   "ElevatorType": "Public",
   "BuildingNumber": 277,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hagerty Hall",
   "Address": "1775 College Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "45905",
   "ElevatorType": "Public",
   "BuildingNumber": 37,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hagerty Hall",
   "Address": "1775 College Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "45906",
   "ElevatorType": "Public",
   "BuildingNumber": 37,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hale Hall",
   "Address": "154 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "28388",
   "ElevatorType": "Public",
   "BuildingNumber": 85,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hale Hall",
   "Address": "154 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "28387",
   "ElevatorType": "Public",
   "BuildingNumber": 85,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hamilton Hall",
   "Address": "1645 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "1378",
   "ElevatorType": "Public",
   "BuildingNumber": 38,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hamilton Hall",
   "Address": "1645 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "1377",
   "ElevatorType": "Staff",
   "BuildingNumber": 38,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hamilton Hall",
   "Address": "1645 Neil Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "31370",
   "ElevatorType": "Public",
   "BuildingNumber": 38,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hayes Hall",
   "Address": "108 N Oval Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "24955",
   "ElevatorType": "Public",
   "BuildingNumber": 39,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hitchcock Hall",
   "Address": "2070 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "1024",
   "ElevatorType": "Public",
   "BuildingNumber": 274,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hitchcock Hall",
   "Address": "2070 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "1025",
   "ElevatorType": "Freight",
   "BuildingNumber": 274,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hopkins Hall",
   "Address": "128 N Oval Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "6279",
   "ElevatorType": "Public",
   "BuildingNumber": 149,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Howlett Greenhouses",
   "Address": "680 Vernon Tharp St",
   "ElevatorNumber": "1",
   "AssetNumber": "291",
   "ElevatorType": "Public",
   "BuildingNumber": 297,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Howlett Hall",
   "Address": "2001 Fyffe Ct",
   "ElevatorNumber": "1",
   "AssetNumber": "290",
   "ElevatorType": "Public",
   "BuildingNumber": 295,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hughes Hall",
   "Address": "1899 College Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "44438",
   "ElevatorType": "Public",
   "BuildingNumber": 42,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Hughes Hall",
   "Address": "1899 College Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "28837",
   "ElevatorType": "Public",
   "BuildingNumber": 42,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Jennings Hall",
   "Address": "1735 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "33629",
   "ElevatorType": "Public",
   "BuildingNumber": 14,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Jennings Hall",
   "Address": "1735 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "49063",
   "ElevatorType": "Public",
   "BuildingNumber": 14,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Jennings Hall",
   "Address": "1735 Neil Ave",
   "ElevatorNumber": "3-Northwest",
   "AssetNumber": "",
   "ElevatorType": "Public",
   "BuildingNumber": 14,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Jennings Hall",
   "Address": "1735 Neil Ave",
   "ElevatorNumber": "4-Southwest",
   "AssetNumber": "",
   "ElevatorType": "Public",
   "BuildingNumber": 14,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Jennings Hall",
   "Address": "1735 Neil Ave",
   "ElevatorNumber": "5-Old",
   "AssetNumber": "",
   "ElevatorType": "Public",
   "BuildingNumber": 14,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Journalism Building",
   "Address": "242 W 18th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "21981",
   "ElevatorType": "Public",
   "BuildingNumber": 46,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Kenny Rd, 1900",
   "Address": "1900 Kenny Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "174",
   "ElevatorType": "Public",
   "BuildingNumber": 232,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Knowlton Executive Terminal",
   "Address": "2160 W Case Rd",
   "ElevatorNumber": "Knowlton Airport Terminal Only",
   "AssetNumber": "",
   "ElevatorType": "Public",
   "BuildingNumber": 1019,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Knowlton Hall",
   "Address": "275 W Woodruff Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "45718",
   "ElevatorType": "Public",
   "BuildingNumber": 17,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Knowlton Hall",
   "Address": "275 W Woodruff Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "45719",
   "ElevatorType": "Public",
   "BuildingNumber": 17,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Knowlton Hall",
   "Address": "275 W Woodruff Ave",
   "ElevatorNumber": "3-Handicap Lift",
   "AssetNumber": "47050",
   "ElevatorType": "Public",
   "BuildingNumber": 17,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Kottman Hall",
   "Address": "2021 Coffey Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "26240",
   "ElevatorType": "Public",
   "BuildingNumber": 340,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Kottman Hall",
   "Address": "2021 Coffey Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "26241",
   "ElevatorType": "Staff",
   "BuildingNumber": 340,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Kottman Hall",
   "Address": "2021 Coffey Rd",
   "ElevatorNumber": "3",
   "AssetNumber": "26242",
   "ElevatorType": "Public",
   "BuildingNumber": 340,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Kuhn Honors and Scholars House",
   "Address": "220 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "32595",
   "ElevatorType": "Public",
   "BuildingNumber": 959,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Lazenby Hall",
   "Address": "1827 Neil Ave Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "24951",
   "ElevatorType": "Public",
   "BuildingNumber": 41,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Lazenby Hall",
   "Address": "1827 Neil Ave Mall",
   "ElevatorNumber": "2",
   "AssetNumber": "30490",
   "ElevatorType": "Public",
   "BuildingNumber": 41,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Longaberger Alumni House",
   "Address": "2200 Olentangy River Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "41222",
   "ElevatorType": "Freight",
   "BuildingNumber": 22,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Longaberger Alumni House",
   "Address": "2200 Olentangy River Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "41223",
   "ElevatorType": "Public",
   "BuildingNumber": 22,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "MacQuigg Laboratory",
   "Address": "105 W Woodruff Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "1077",
   "ElevatorType": "Public",
   "BuildingNumber": 265,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Maintenance Building",
   "Address": "2000 Tuttle Park Pl",
   "ElevatorNumber": "1",
   "AssetNumber": "516",
   "ElevatorType": "Public",
   "BuildingNumber": 78,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mason Hall",
   "Address": "250 W Woodruff Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "40285",
   "ElevatorType": "Public",
   "BuildingNumber": 252,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mason Hall",
   "Address": "250 W Woodruff Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "40286",
   "ElevatorType": "Public",
   "BuildingNumber": 252,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mason Hall",
   "Address": "250 W Woodruff Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "40287",
   "ElevatorType": "Public",
   "BuildingNumber": 252,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mathematics Building",
   "Address": "231 W 18th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "3152",
   "ElevatorType": "Public",
   "BuildingNumber": 187,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mathematics Tower",
   "Address": "231 W 18th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "32412",
   "ElevatorType": "Public",
   "BuildingNumber": 7,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mathematics Tower",
   "Address": "231 W 18th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "32430",
   "ElevatorType": "Public",
   "BuildingNumber": 7,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "McCorkle Aquatic Pavilion",
   "Address": "1847 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "47047",
   "ElevatorType": "Public",
   "BuildingNumber": 247,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "McCorkle Aquatic Pavilion",
   "Address": "1847 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "47048",
   "ElevatorType": "Freight",
   "BuildingNumber": 247,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "McCracken Power Plant",
   "Address": "2001 Millikin Road",
   "ElevatorNumber": "1",
   "AssetNumber": "",
   "ElevatorType": "Public",
   "BuildingNumber": 69,
   "Contractor": "Fujitec",
   "DispatchPhone": "614-292-2847",
   "Guideline": 2
 },
 {
   "BuildingName": "McCracken Power Plant",
   "Address": "2001 Millikin Road",
   "ElevatorNumber": "2",
   "AssetNumber": "",
   "ElevatorType": "Freight",
   "BuildingNumber": 69,
   "Contractor": "Fujitec",
   "DispatchPhone": "614-292-2847",
   "Guideline": 2
 },
 {
   "BuildingName": "McPhereson Chemical Laboratory",
   "Address": "140 W 18th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "40414",
   "ElevatorType": "Public",
   "BuildingNumber": 53,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "McPhereson Chemical Laboratory",
   "Address": "140 W 18th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "40415",
   "ElevatorType": "Public",
   "BuildingNumber": 53,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Meiling Hall",
   "Address": "370 W 9th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "427",
   "ElevatorType": "Public",
   "BuildingNumber": 281,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Meiling Hall",
   "Address": "370 W 9th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "432",
   "ElevatorType": "Public",
   "BuildingNumber": 281,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Meiling Hall",
   "Address": "370 W 9th Ave",
   "ElevatorNumber": "3-Tunnel",
   "AssetNumber": "431",
   "ElevatorType": "Public",
   "BuildingNumber": 281,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mendenhall Laboratory",
   "Address": "125 S Oval Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "33773",
   "ElevatorType": "Public",
   "BuildingNumber": 54,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mershon Auditorium",
   "Address": "1871 N High St",
   "ElevatorNumber": "9",
   "AssetNumber": "6295",
   "ElevatorType": "Public",
   "BuildingNumber": 55,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mershon Center",
   "Address": "1501 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "22046",
   "ElevatorType": "Public",
   "BuildingNumber": 47,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mershon Center",
   "Address": "1501 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "33057",
   "ElevatorType": "Staff",
   "BuildingNumber": 47,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mount Hall",
   "Address": "1050 Carmack Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "22042",
   "ElevatorType": "Freight",
   "BuildingNumber": 311,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Mount Hall",
   "Address": "1050 Carmack Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "63643",
   "ElevatorType": "Public",
   "BuildingNumber": 311,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Newman and Wolfram Laboratory of Chemistry",
   "Address": "100 W 18th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "33889",
   "ElevatorType": "Public",
   "BuildingNumber": 147,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Newton Hall",
   "Address": "1585 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "2266",
   "ElevatorType": "Public",
   "BuildingNumber": 275,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Newton Hall",
   "Address": "1585 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "2267",
   "ElevatorType": "Public",
   "BuildingNumber": 275,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Nineteenth Ave, 140 W",
   "Address": "140 W 19th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "6503",
   "ElevatorType": "Public",
   "BuildingNumber": 145,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Northwood-High Building",
   "Address": "2231 N High St",
   "ElevatorNumber": "1",
   "AssetNumber": "33726",
   "ElevatorType": "Public",
   "BuildingNumber": 357,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Northwood-High Building",
   "Address": "2231 N High St",
   "ElevatorNumber": "2",
   "AssetNumber": "33728",
   "ElevatorType": "Public",
   "BuildingNumber": 357,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Ohio Stadium",
   "Address": "411 Woody Hayes Dr",
   "ElevatorNumber": "1-Gate 26",
   "AssetNumber": "286",
   "ElevatorType": "Public",
   "BuildingNumber": 82,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Ohio Stadium",
   "Address": "411 Woody Hayes Dr",
   "ElevatorNumber": "2-Gate 18-20",
   "AssetNumber": "346",
   "ElevatorType": "Public",
   "BuildingNumber": 82,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Orton Hall",
   "Address": "155 S Oval Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "25834",
   "ElevatorType": "Public",
   "BuildingNumber": 60,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Oxley Hall",
   "Address": "1712 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "31868",
   "ElevatorType": "Public",
   "BuildingNumber": 102,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Page Hall",
   "Address": "1810 College Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "47137",
   "ElevatorType": "Public",
   "BuildingNumber": 61,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Page Hall",
   "Address": "1810 College Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "47138",
   "ElevatorType": "Public",
   "BuildingNumber": 61,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Parker Food Science and Technology",
   "Address": "2015 Fyffe Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "41965",
   "ElevatorType": "Public",
   "BuildingNumber": 64,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Parker Food Science and Technology",
   "Address": "2015 Fyffe Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "41966",
   "ElevatorType": "Public",
   "BuildingNumber": 64,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Parks Hall",
   "Address": "500 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "27299",
   "ElevatorType": "Public",
   "BuildingNumber": 273,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Parks Hall",
   "Address": "500 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "6548",
   "ElevatorType": "Public",
   "BuildingNumber": 273,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Pfahl Hall",
   "Address": "280 W Woodruff Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "40288",
   "ElevatorType": "Public",
   "BuildingNumber": 253,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Pfahl Hall",
   "Address": "280 W Woodruff Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "40289",
   "ElevatorType": "Public",
   "BuildingNumber": 253,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Physical Activity and Educations Services (PAES)",
   "Address": "305 Annie & John Glenn Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "47043",
   "ElevatorType": "Public",
   "BuildingNumber": 245,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Physical Activity and Educations Services (PAES)",
   "Address": "305 Annie & John Glenn Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "47044",
   "ElevatorType": "Public",
   "BuildingNumber": 245,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Physics Research Building",
   "Address": "191 W Woodruff Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "46147",
   "ElevatorType": "Public",
   "BuildingNumber": 70,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Physics Research Building",
   "Address": "191 W Woodruff Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "46148",
   "ElevatorType": "Public",
   "BuildingNumber": 70,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Physics Research Building",
   "Address": "191 W Woodruff Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "46149",
   "ElevatorType": "Freight",
   "BuildingNumber": 70,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Pizzuti House",
   "Address": "80 North Drexel, Bexley OH 43209",
   "ElevatorNumber": "1",
   "AssetNumber": "TBD",
   "ElevatorType": "Public",
   "BuildingNumber": 950,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Plumb Hall",
   "Address": "2027 Coffey Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "706",
   "ElevatorType": "Public",
   "BuildingNumber": 66,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Pomerene Hall",
   "Address": "1760 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "",
   "ElevatorType": "Public",
   "BuildingNumber": 67,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Postle Hall",
   "Address": "305 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "8570",
   "ElevatorType": "Public",
   "BuildingNumber": 24,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Postle Hall",
   "Address": "305 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "8569",
   "ElevatorType": "Public",
   "BuildingNumber": 24,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Postle Hall",
   "Address": "305 W 12th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "6307",
   "ElevatorType": "Public",
   "BuildingNumber": 24,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Postle Hall",
   "Address": "305 W 12th Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "28399",
   "ElevatorType": "Public",
   "BuildingNumber": 24,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Postle Hall",
   "Address": "305 W 12th Ave",
   "ElevatorNumber": "6",
   "AssetNumber": "20973",
   "ElevatorType": "Public",
   "BuildingNumber": 24,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Postle Hall",
   "Address": "305 W 12th Ave",
   "ElevatorNumber": "7",
   "AssetNumber": "20974",
   "ElevatorType": "Public",
   "BuildingNumber": 24,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Pressey Hall",
   "Address": "1070 Carmack Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "555",
   "ElevatorType": "Public",
   "BuildingNumber": 309,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Prior Hall",
   "Address": "376 W 10th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "771",
   "ElevatorType": "Public",
   "BuildingNumber": 302,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Prior Hall",
   "Address": "376 W 10th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "783",
   "ElevatorType": "Public",
   "BuildingNumber": 302,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Prior Hall",
   "Address": "376 W 10th Ave",
   "ElevatorNumber": "3-South",
   "AssetNumber": "786",
   "ElevatorType": "Public",
   "BuildingNumber": 302,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Prior Hall",
   "Address": "376 W 10th Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "787",
   "ElevatorType": "Public",
   "BuildingNumber": 302,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Prior Hall",
   "Address": "376 W 10th Ave",
   "ElevatorNumber": "5",
   "AssetNumber": "35286",
   "ElevatorType": "Staff",
   "BuildingNumber": 302,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Psychology Building",
   "Address": "1835 Neil Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "47600",
   "ElevatorType": "Public",
   "BuildingNumber": 144,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Psychology Building",
   "Address": "1835 Neil Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "47601",
   "ElevatorType": "Public",
   "BuildingNumber": 144,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Ramseyer Hall",
   "Address": "29 W Woodruff Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "28810",
   "ElevatorType": "Public",
   "BuildingNumber": 90,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Research Foundation",
   "Address": "1960 Kenny Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "20976",
   "ElevatorType": "Public",
   "BuildingNumber": 200,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Research Foundation",
   "Address": "1960 Kenny Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "20977",
   "ElevatorType": "Public",
   "BuildingNumber": 200,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Research Foundation",
   "Address": "1960 Kenny Rd",
   "ElevatorNumber": "3",
   "AssetNumber": "",
   "ElevatorType": "Public",
   "BuildingNumber": 200,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Riffe Building",
   "Address": "496 W 12th Ave",
   "ElevatorNumber": "1-North",
   "AssetNumber": "33053",
   "ElevatorType": "Public",
   "BuildingNumber": 266,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Riffe Building",
   "Address": "496 W 12th Ave",
   "ElevatorNumber": "2-South",
   "AssetNumber": "33054",
   "ElevatorType": "Public",
   "BuildingNumber": 266,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Riffe Building",
   "Address": "496 W 12th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "33055",
   "ElevatorType": "Public",
   "BuildingNumber": 266,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Riffe Building",
   "Address": "496 W 12th Ave",
   "ElevatorNumber": "4- Library",
   "AssetNumber": "33056",
   "ElevatorType": "Staff",
   "BuildingNumber": 266,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Rightmire Hall",
   "Address": "1060 Carmack Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "357",
   "ElevatorType": "Public",
   "BuildingNumber": 308,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Rightmire Hall",
   "Address": "1060 Carmack Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "31762",
   "ElevatorType": "Staff",
   "BuildingNumber": 308,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "RPAC (Recreational and Physical Activity Center)",
   "Address": "337 Annie & John Glenn Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "47045",
   "ElevatorType": "Public",
   "BuildingNumber": 246,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "RPAC (Recreational and Physical Activity Center)",
   "Address": "337 Annie & John Glenn Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "47046",
   "ElevatorType": "Public",
   "BuildingNumber": 246,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Schoenbaum Family Center",
   "Address": "175 E 7th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "48979",
   "ElevatorType": "Public",
   "BuildingNumber": 933,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Schoenbaum Hall",
   "Address": "210 W Woodruff Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "40280",
   "ElevatorType": "Public",
   "BuildingNumber": 251,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Schoenbaum Hall",
   "Address": "210 W Woodruff Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "40284",
   "ElevatorType": "Public",
   "BuildingNumber": 251,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Scott Hall",
   "Address": "1090 Carmack Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "554",
   "ElevatorType": "Public",
   "BuildingNumber": 310,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Scott Laboratory",
   "Address": "201 W 19th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "47831",
   "ElevatorType": "Public",
   "BuildingNumber": 148,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Scott Laboratory",
   "Address": "201 W 19th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "47832",
   "ElevatorType": "Public",
   "BuildingNumber": 148,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Scott Laboratory",
   "Address": "201 W 19th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "47833",
   "ElevatorType": "Public",
   "BuildingNumber": 148,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sisson Hall",
   "Address": "1920 Coffey Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "28646",
   "ElevatorType": "Public",
   "BuildingNumber": 80,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sisson Hall",
   "Address": "1920 Coffey Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "43810",
   "ElevatorType": "Freight",
   "BuildingNumber": 80,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sisson Hall",
   "Address": "1920 Coffey Rd",
   "ElevatorNumber": "3",
   "AssetNumber": "",
   "ElevatorType": "Public",
   "BuildingNumber": 80,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Smith Laboratory",
   "Address": "174 W 18th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "3208",
   "ElevatorType": "Freight",
   "BuildingNumber": 65,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Smith Laboratory",
   "Address": "174 W 18th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "8807",
   "ElevatorType": "Public",
   "BuildingNumber": 65,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Smith Laboratory",
   "Address": "174 W 18th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "60000",
   "ElevatorType": "Public",
   "BuildingNumber": 65,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "St John Arena",
   "Address": "410 Woody Hayes Dr",
   "ElevatorNumber": "1",
   "AssetNumber": "6344",
   "ElevatorType": "Public",
   "BuildingNumber": 76,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Starling Loving Hall",
   "Address": "320 W 10th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "1386",
   "ElevatorType": "Public",
   "BuildingNumber": 176,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Starling Loving Hall",
   "Address": "320 W 10th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "9213",
   "ElevatorType": "Public",
   "BuildingNumber": 176,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Starling Loving Hall",
   "Address": "320 W 10th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "9214",
   "ElevatorType": "Public",
   "BuildingNumber": 176,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Starling Loving Hall",
   "Address": "320 W 10th Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "19309",
   "ElevatorType": "Public",
   "BuildingNumber": 176,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Starling Loving Hall",
   "Address": "320 W 10th Ave",
   "ElevatorNumber": "5-M Wing",
   "AssetNumber": "TBD",
   "ElevatorType": "Public",
   "BuildingNumber": 176,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Starling Loving Hall",
   "Address": "320 W 10th Ave",
   "ElevatorNumber": "6-M Wing",
   "AssetNumber": "TBD",
   "ElevatorType": "Public",
   "BuildingNumber": 176,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Stillman Hall",
   "Address": "1947 College Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "24954",
   "ElevatorType": "Public",
   "BuildingNumber": 84,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Stillman Hall",
   "Address": "1947 College Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "41354",
   "ElevatorType": "Public",
   "BuildingNumber": 84,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Student Academic Services (SAS)",
   "Address": "281 W Lane Ave",
   "ElevatorNumber": "25",
   "AssetNumber": "51073",
   "ElevatorType": "Public",
   "BuildingNumber": 160,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Student Academic Services (SAS)",
   "Address": "281 W Lane Ave",
   "ElevatorNumber": "26",
   "AssetNumber": "51074",
   "ElevatorType": "Public",
   "BuildingNumber": 160,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Student Academic Services (SAS)",
   "Address": "281 W Lane Ave",
   "ElevatorNumber": "27",
   "AssetNumber": "51075",
   "ElevatorType": "Public",
   "BuildingNumber": 160,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Student Academic Services (SAS)",
   "Address": "281 W Lane Ave",
   "ElevatorNumber": "28",
   "AssetNumber": "51069",
   "ElevatorType": "Freight",
   "BuildingNumber": 160,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sullivant Hall",
   "Address": "1813 N High St",
   "ElevatorNumber": "1",
   "AssetNumber": "61547",
   "ElevatorType": "Public",
   "BuildingNumber": 106,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sullivant Hall",
   "Address": "1813 N High St",
   "ElevatorNumber": "2",
   "AssetNumber": "61549",
   "ElevatorType": "Public",
   "BuildingNumber": 106,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sullivant Hall",
   "Address": "1813 N High St",
   "ElevatorNumber": "3-Chair Lift",
   "AssetNumber": "61550",
   "ElevatorType": "Public",
   "BuildingNumber": 106,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sullivant Hall",
   "Address": "1813 N High St",
   "ElevatorNumber": "4",
   "AssetNumber": "61805",
   "ElevatorType": "Public",
   "BuildingNumber": 106,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sullivant Hall",
   "Address": "1813 N High St",
   "ElevatorNumber": "5-E.H.S Library",
   "AssetNumber": "TBD",
   "ElevatorType": "Public",
   "BuildingNumber": 106,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sullivant Hall",
   "Address": "1813 N High St",
   "ElevatorNumber": "6",
   "AssetNumber": "TBD",
   "ElevatorType": "Freight",
   "BuildingNumber": 106,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sullivant Hall",
   "Address": "1813 N High St",
   "ElevatorNumber": "7-Music Library",
   "AssetNumber": "TBD",
   "ElevatorType": "Public",
   "BuildingNumber": 106,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Sullivant Hall",
   "Address": "1813 N High St",
   "ElevatorNumber": "8-Rotunda",
   "AssetNumber": "TBD",
   "ElevatorType": "Public",
   "BuildingNumber": 106,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Telecommunications Network Center",
   "Address": "320 W 8th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "28817",
   "ElevatorType": "Public",
   "BuildingNumber": 379,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Thompson Library",
   "Address": "1858 Neil Mall Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "50349",
   "ElevatorType": "Public",
   "BuildingNumber": 50,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Thompson Library",
   "Address": "1858 Neil Mall Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "50353",
   "ElevatorType": "Public",
   "BuildingNumber": 50,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Thompson Library",
   "Address": "1858 Neil Mall Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "50350",
   "ElevatorType": "Public",
   "BuildingNumber": 50,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Thompson Library",
   "Address": "1858 Neil Mall Ave",
   "ElevatorNumber": "4",
   "AssetNumber": "50351",
   "ElevatorType": "Public",
   "BuildingNumber": 50,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Thompson Library",
   "Address": "1858 Neil Mall Ave",
   "ElevatorNumber": "5",
   "AssetNumber": "50352",
   "ElevatorType": "Public",
   "BuildingNumber": 50,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Townshend Hall",
   "Address": "1885 Neil Ave Mall",
   "ElevatorNumber": "1",
   "AssetNumber": "27285",
   "ElevatorType": "Public",
   "BuildingNumber": 87,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Tzagournis Medical Research Facility",
   "Address": "420 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "33476",
   "ElevatorType": "Public",
   "BuildingNumber": 163,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Tzagournis Medical Research Facility",
   "Address": "420 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "33477",
   "ElevatorType": "Public",
   "BuildingNumber": 163,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Tzagournis Medical Research Facility",
   "Address": "420 W 12th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "47631",
   "ElevatorType": "Staff",
   "BuildingNumber": 163,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "University Hall",
   "Address": "230 N Oval Mall",
   "ElevatorNumber": "1-East",
   "AssetNumber": "22544",
   "ElevatorType": "Public",
   "BuildingNumber": 339,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "University Hall",
   "Address": "230 N Oval Mall",
   "ElevatorNumber": "2-West",
   "AssetNumber": "22545",
   "ElevatorType": "Public",
   "BuildingNumber": 339,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Veterinary Medical Center",
   "Address": "601 Vernon L. Tharp St",
   "ElevatorNumber": "1",
   "AssetNumber": "20746",
   "ElevatorType": "Public",
   "BuildingNumber": 299,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Veterinary Medical Center",
   "Address": "601 Vernon L. Tharp St",
   "ElevatorNumber": "2",
   "AssetNumber": "20747",
   "ElevatorType": "Public",
   "BuildingNumber": 299,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Veterinary Medical Center",
   "Address": "601 Vernon L. Tharp St",
   "ElevatorNumber": "3",
   "AssetNumber": "63178",
   "ElevatorType": "Staff",
   "BuildingNumber": 299,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Veterinary Medical Center",
   "Address": "601 Vernon Tharp St",
   "ElevatorNumber": "4",
   "AssetNumber": "65113",
   "ElevatorType": "Public",
   "BuildingNumber": 299,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Veterinary Medicine Academic",
   "Address": "1900 Coffey Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "43618",
   "ElevatorType": "Public",
   "BuildingNumber": 136,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Veterinary Medicine Academic",
   "Address": "1900 Coffey Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "43809",
   "ElevatorType": "Public",
   "BuildingNumber": 136,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Veterinary Medicine Academic",
   "Address": "1900 Coffey Rd",
   "ElevatorNumber": "3",
   "AssetNumber": "44440",
   "ElevatorType": "Public",
   "BuildingNumber": 136,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Veterinary Medicine Academic",
   "Address": "1900 Coffey Rd",
   "ElevatorNumber": "4",
   "AssetNumber": "45983",
   "ElevatorType": "Public",
   "BuildingNumber": 136,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Watts Hall",
   "Address": "2041 College Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "6292",
   "ElevatorType": "Public",
   "BuildingNumber": 107,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Weigel Hall",
   "Address": "1866 College Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "24578",
   "ElevatorType": "Public",
   "BuildingNumber": 355,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Weigel Hall",
   "Address": "1866 College Rd",
   "ElevatorNumber": "2",
   "AssetNumber": "TBD",
   "ElevatorType": "Freight",
   "BuildingNumber": 355,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "1",
   "AssetNumber": "30519",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "2",
   "AssetNumber": "30520",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "3",
   "AssetNumber": "30521",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "4",
   "AssetNumber": "30577",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "5",
   "AssetNumber": "30578",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "6 - Main Library",
   "AssetNumber": "30522",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "7 - Cartoon Library",
   "AssetNumber": "30523",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "8 - Fine Arts Library",
   "AssetNumber": "30576",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N Hight St",
   "ElevatorNumber": "9 - Escalator, Down",
   "AssetNumber": "48015",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wexner Center for the Arts",
   "Address": "1871 N High St",
   "ElevatorNumber": "10 - Escalator, Up",
   "AssetNumber": "48016",
   "ElevatorType": "Public",
   "BuildingNumber": 386,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wilce Student Health Center",
   "Address": "1875 Millikin Rd",
   "ElevatorNumber": "1",
   "AssetNumber": "488",
   "ElevatorType": "Public",
   "BuildingNumber": 294,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wiseman Hall",
   "Address": "400 W 12th Ave",
   "ElevatorNumber": "1",
   "AssetNumber": "2530",
   "ElevatorType": "Public",
   "BuildingNumber": 157,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wiseman Hall",
   "Address": "400 W 12th Ave",
   "ElevatorNumber": "2",
   "AssetNumber": "733",
   "ElevatorType": "Public",
   "BuildingNumber": 157,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 },
 {
   "BuildingName": "Wiseman Hall",
   "Address": "400 W 12th Ave",
   "ElevatorNumber": "3",
   "AssetNumber": "46591",
   "ElevatorType": "Staff",
   "BuildingNumber": 157,
   "Contractor": "Thyssen Krupp Elevator",
   "DispatchPhone": "(614)-895-8930",
   "Guideline": 1
 }
]